-- MySQL Script generated by MySQL Workbench
-- Sun Aug 18 19:50:52 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hoteldb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `hoteldb` ;

-- -----------------------------------------------------
-- Schema hoteldb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hoteldb` DEFAULT CHARACTER SET utf8 ;
USE `hoteldb` ;

-- -----------------------------------------------------
-- Table `hoteldb`.`hotel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoteldb`.`hotel`;

CREATE TABLE IF NOT EXISTS `hoteldb`.`hotel` (
  `id_hotel` CHAR(36) NOT NULL DEFAULT (UUID()),  -- Cambiar a CHAR(36) y generar UUID
  `name` VARCHAR(45) NULL,
  `location` VARCHAR(45) NULL,
  PRIMARY KEY (`id_hotel`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `hoteldb`.`room`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoteldb`.`room`;

CREATE TABLE IF NOT EXISTS `hoteldb`.`room` (
  `id_room` CHAR(36) NOT NULL DEFAULT (UUID()),  -- Cambiar a CHAR(36) y generar UUID
  `number` INT NULL,
  `unit_price` DOUBLE NULL,
  `floor` INT NULL,
  `maintenance` DOUBLE NULL,
  `description` VARCHAR(200) NULL,
  `occupied` BOOLEAN NOT NULL DEFAULT FALSE,
  `hotel_id_hotel` CHAR(36) NOT NULL,  -- Cambiar tipo de dato para foreign key
  PRIMARY KEY (`id_room`),
  INDEX `fk_room_hotel1_idx` (`hotel_id_hotel` ASC) VISIBLE,
  CONSTRAINT `fk_room_hotel1`
    FOREIGN KEY (`hotel_id_hotel`)
    REFERENCES `hoteldb`.`hotel` (`id_hotel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `hoteldb`.`maintenance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hoteldb`.`maintenance`;

CREATE TABLE IF NOT EXISTS `hoteldb`.`maintenance` (
  `id_maintenance` CHAR(36) NOT NULL DEFAULT (UUID()),  -- Generar UUID
  `date_maintenance` DATE NULL,
  `maintenance` DOUBLE NULL,
  `room_id_room` CHAR(36) NOT NULL,  -- Tipo de dato para foreign key
  PRIMARY KEY (`id_maintenance`),
  INDEX `fk_maintenance_room1_idx` (`room_id_room` ASC) VISIBLE,
  CONSTRAINT `fk_maintenance_room1`
    FOREIGN KEY (`room_id_room`)
    REFERENCES `hoteldb`.`room` (`id_room`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;




SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



INSERT INTO `hoteldb`.`hotel` (`id_hotel`, `name`, `location`)
VALUES 
    ('111febee-b7a4-4691-b5a0-29fdcd4618fa', 'Hotel Example 1', 'Location 1'),
    ('222febee-b7a4-4691-b5a0-29fdcd4618fa', 'Hotel Example 2', 'Location 2'),
    ('333febee-b7a4-4691-b5a0-29fdcd4618fa', 'Hotel Example 3', 'Location 3'),
    ('444febee-b7a4-4691-b5a0-29fdcd4618fa', 'Hotel Example 4', 'Location 4'),
    ('555febee-b7a4-4691-b5a0-29fdcd4618fa', 'Hotel Example 5', 'Location 5');

INSERT INTO `hoteldb`.`room` (`id_room`, `number`, `unit_price`, `floor`, `maintenance`, `description`, `occupied`, `hotel_id_hotel`)
VALUES 
    ('111febee-b7a4-4691-b5a0-29fdcd4618fb', 1, 100.0, 1, 20.0, 'Single room with a view', FALSE, '111febee-b7a4-4691-b5a0-29fdcd4618fa'),
    ('112febee-b7a4-4691-b5a0-29fdcd4618fb', 2, 120.0, 1, 25.0, 'Double room with balcony', FALSE, '222febee-b7a4-4691-b5a0-29fdcd4618fa'),
    ('113febee-b7a4-4691-b5a0-29fdcd4618fb', 3, 150.0, 1, 15.0, 'Suite with king bed', FALSE, '333febee-b7a4-4691-b5a0-29fdcd4618fa'),
    ('114febee-b7a4-4691-b5a0-29fdcd4618fb', 4, 180.0, 1, 30.0, 'Deluxe room with spa bath', FALSE, '444febee-b7a4-4691-b5a0-29fdcd4618fa'),
    ('115febee-b7a4-4691-b5a0-29fdcd4618fb', 5, 100.0, 1, 10.0, 'Basic Room', FALSE, '444febee-b7a4-4691-b5a0-29fdcd4618fa'),
    ('116febee-b7a4-4691-b5a0-29fdcd4618fb', 5, 200.0, 1, 10.0, 'Presidential suite with panoramic view', FALSE, '555febee-b7a4-4691-b5a0-29fdcd4618fa');





