-- MySQL Script generated by MySQL Workbench
-- Sun Aug 31 20:05:24 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema promotiondb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `promotiondb` ;

-- -----------------------------------------------------
-- Schema promotiondb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `promotiondb` DEFAULT CHARACTER SET utf8 ;
USE `promotiondb` ;

-- -----------------------------------------------------
-- Table `promotiondb`.`promotion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `promotiondb`.`promotion` ;

CREATE TABLE IF NOT EXISTS `promotiondb`.`promotion` (
  `id_promotion` CHAR(36) NOT NULL DEFAULT (UUID()),
  `start_date` DATE NULL,
  `end_date` DATE NULL,
  `type` VARCHAR(45) NULL,
  `description` VARCHAR(200) NULL,
  `type_client` VARCHAR(45) NULL,
  `id_product` CHAR(36) NOT NULL,
  `value_promotion` DOUBLE NULL,
  PRIMARY KEY (`id_promotion`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `hoteldb`.`comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `promotiondb`.`comment`;

CREATE TABLE IF NOT EXISTS `promotiondb`.`comment` (
  `id_comment` CHAR(36) NOT NULL DEFAULT (UUID()),  -- Generar UUID
  `date_comment` DATE NULL,
  `description` VARCHAR(200) NULL,
  `type` VARCHAR(50) NULL,
  `rate` DOUBLE NULL,
  `id_product` CHAR(36) NOT NULL,
  `user_id_user` CHAR(36) NOT NULL,
  PRIMARY KEY (`id_comment`))
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

