-- MySQL Script generated by MySQL Workbench
-- Date: Aug 31, 2024
-- Model: User Domain Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema userdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `userdb`;

CREATE SCHEMA IF NOT EXISTS `userdb` DEFAULT CHARACTER SET utf8;
USE `userdb`;

-- -----------------------------------------------------
-- Table `userdb`.`client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `userdb`.`client`;

CREATE TABLE IF NOT EXISTS `userdb`.`client` (
  `id` CHAR(36) NOT NULL DEFAULT (UUID()),
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(20) NULL,
  `type` VARCHAR(50) NULL,
  `role` ENUM('ADMINISTRATOR', 'EMPLOYEE', 'CUSTOMER') NULL,
  `expiration_date` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `userdb`.`employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `userdb`.`employee`;

CREATE TABLE IF NOT EXISTS `userdb`.`employee` (
  `id` CHAR(36) NOT NULL DEFAULT (UUID()),
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(20) NULL,
  `type` VARCHAR(50) NULL,
  `weekly_payment` DECIMAL(10, 2) NULL,
  `id_location` CHAR(36) NULL,
  `role` ENUM('ADMINISTRATOR', 'EMPLOYEE', 'CUSTOMER') NULL,
  `expiration_date` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `userdb`.`payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `userdb`.`payment`;

CREATE TABLE IF NOT EXISTS `userdb`.`payment` (
  `id` CHAR(36) NOT NULL DEFAULT (UUID()),
  `date_payment` DATE NOT NULL,
  `payment` DECIMAL(10, 2) NOT NULL,
  `id_employee` CHAR(36) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_payment_employee_idx` (`id_employee` ASC) VISIBLE,
  CONSTRAINT `fk_payment_employee`
    FOREIGN KEY (`id_employee`)
    REFERENCES `userdb`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



INSERT INTO `userdb`.`client` (`id`, `email`, `password`, `name`, `phone`, `type`, `role`, `expiration_date`)
VALUES 
    ('1dc06405-e451-4095-b76b-fcccaeaaac96', 'alice.smith@example.com', '$2a$10$0CGCWSNjLedf1EtxLn6cxOzl760ZKv4ZKw5SHSwJ0Goyay5cjk1nm', 'Alice Smith', '1234567890', 'Regular', 'CUSTOMER', '2025-12-31 23:59:59'),
    ('2dc06405-e451-4095-b76b-fcccaeaaac96', 'bob.johnson@example.com', '$2a$10$0CGCWSNjLedf1EtxLn6cxOzl760ZKv4ZKw5SHSwJ0Goyay5cjk1nm', 'Bob Johnson', '2345678901', 'Regular', 'CUSTOMER', '2025-11-30 23:59:59'),
    ('3dc06405-e451-4095-b76b-fcccaeaaac96', 'carol.davis@example.com', '$2a$10$0CGCWSNjLedf1EtxLn6cxOzl760ZKv4ZKw5SHSwJ0Goyay5cjk1nm', 'Carol Davis', '3456789012', 'Regular', 'CUSTOMER', '2025-10-31 23:59:59'),
    ('4dc06405-e451-4095-b76b-fcccaeaaac96', 'david.wilson@example.com', '$2a$10$0CGCWSNjLedf1EtxLn6cxOzl760ZKv4ZKw5SHSwJ0Goyay5cjk1nm', 'David Wilson', '4567890123', 'Regular', 'CUSTOMER', '2025-09-30 23:59:59'),
    ('5dc06405-e451-4095-b76b-fcccaeaaac96', 'eve.martin@example.com', '$2a$10$0CGCWSNjLedf1EtxLn6cxOzl760ZKv4ZKw5SHSwJ0Goyay5cjk1nm', 'Eve Martin', '5678901234', 'Regular', 'CUSTOMER', '2025-08-31 23:59:59'),
    ('6dc06405-e451-4095-b76b-fcccaeaaac96', 'exe.mart1n@example.com', '$2a$10$0CGCWSNjLedf1EtxLn6cxOzl760ZKv4ZKw5SHSwJ0Goyay5cjk1nm', 'Exe Mart1n', '5678901234', 'Regular', 'CUSTOMER', '2025-08-31 23:59:59'),
    ('7dc06405-e451-4095-b76b-fcccaeaaac96', 'rol.ratin1@example.com', '$2a$10$0CGCWSNjLedf1EtxLn6cxOzl760ZKv4ZKw5SHSwJ0Goyay5cjk1nm', 'Rol Ratin', '5678901234', 'Regular', 'CUSTOMER', '2025-08-31 23:59:59'),
    ('8dc06405-e451-4095-b76b-fcccaeaaac96', 'carolima11@example.com', '$2a$10$0CGCWSNjLedf1EtxLn6cxOzl760ZKv4ZKw5SHSwJ0Goyay5cjk1nm', 'Carolina E', '5678901234', 'Regular', 'CUSTOMER', '2025-08-31 23:59:59'),
    ('9dc06405-e451-4095-b76b-fcccaeaaac96', 'asdffdsaaa@example.com', '$2a$10$0CGCWSNjLedf1EtxLn6cxOzl760ZKv4ZKw5SHSwJ0Goyay5cjk1nm', 'Pedro Pasc', '5678901234', 'Regular', 'CUSTOMER', '2025-08-31 23:59:59'),
    ('10c06405-e451-4095-b76b-fcccaeaaac96', 'martinScor@example.com', '$2a$10$0CGCWSNjLedf1EtxLn6cxOzl760ZKv4ZKw5SHSwJ0Goyay5cjk1nm', 'Martin Sco', '5678901234', 'Regular', 'CUSTOMER', '2025-08-31 23:59:59');


INSERT INTO `userdb`.`employee` (`id`, `email`, `password`, `name`, `phone`, `type`, `weekly_payment`, `id_location`, `role`, `expiration_date`)
VALUES 
    ('1gg06405-e451-4095-b76b-fcccaeaaac96', 'john.emp@example.com', '$2a$04$examplehashfordemo', 'John Doe', '1112223333', 'EMPLOYEE', 500.00, '011febee-b7a4-4691-b5a0-29fdcd4618fa', 'EMPLOYEE', '2025-12-31 23:59:59'),
    ('2gg06405-e451-4095-b76b-fcccaeaaac96', 'jane.emp@example.com', '$2a$04$examplehashfordemo', 'Jane Smith', '2223334444', 'EMPLOYEE', 250.00, '022febee-b7a4-4691-b5a0-29fdcd4618fa', 'EMPLOYEE', '2025-11-30 23:59:59'),
    ('3gg06405-e451-4095-b76b-fcccaeaaac96', 'alice.emp@example.com', '$2a$04$examplehashfordemo', 'Alice Jones', '3334445555', 'EMPLOYEE', 600.00, '111febee-b7a4-4691-b5a0-29fdcd4618fa', 'ADMINISTRATOR', '2025-10-31 23:59:59'),
    ('4gg06405-e451-4095-b76b-fcccaeaaac96', 'bob.emp@example.com', '$2a$04$examplehashfordemo', 'Bob Brown', '4445556666', 'EMPLOYEE', 400.00, '222febee-b7a4-4691-b5a0-29fdcd4618fa', 'EMPLOYEE', '2025-09-30 23:59:59'),
    ('5gg06405-e451-4095-b76b-fcccaeaaac96', 'carol.emp@example.com', '$2a$04$examplehashfordemo', 'Carol Davis', '5556667777', 'EMPLOYEE', 200.00, '011febee-b7a4-4691-b5a0-29fdcd4618fa', 'EMPLOYEE', '2025-08-31 23:59:59');




